version: '2'
  
services:
  server:
    container_name: server
    build: arcgis-server
    image: geoceg/arcgis-server
    environment:
      AGS_USERNAME: ${ARCGIS_USERNAME}
      AGS_PASSWORD: ${ARCGIS_PASSWORD}
    ports:
      - "6080:6080"
      - "6443:6443"
    volumes:
      - "${SERVER_ROOT}/arcgis/config-store:/home/arcgis/server/usr/config-store"
      - "${SERVER_ROOT}/arcgis/directories:/home/arcgis/server/usr/directories"
      - "${SERVER_ROOT}/arcgis/logs:/home/arcgis/server/usr/logs"
    networks:
      - arcgis.net


  portal:
    container_name: portal
    build: portal-for-arcgis
    image: geoceg/portal-for-arcgis
    ports:
      - "7080:7080"
      - "7443:7443"
    volumes:
      - "${SERVER_ROOT}/arcgisportal:/home/arcgis/portal/usr/arcgisportal"
    networks:
      - arcgis.net
    depends_on:
      - server
    restart: on-failure


#  web-adaptor:
#    container_name: web-adaptor
#    build: web-adaptor
#    image: geoceg/web-adaptor
#    ports:
#      - "80:80"
#      - "443:443"
#    links:
#      - "portal"
#      - "server"
#      - "datastore"
#    networks:
#      - arcgis.net


  datastore:
    container_name: datastore
    build: datastore
    image: geoceg/datastore
    environment:
      AGS_USER: ${ARCGIS_USERNAME}
      AGS_PASSWORD: ${ARCGIS_PASSWORD}
      AGS_DOMAIN: ${ARCGIS_DOMAIN}
    ports:
      - "2443:2443"
    networks:
      - arcgis.net


networks:
  arcgis.net:
    driver: bridge
